# Generated by Django 5.0.1 on 2024-02-06 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2024, 2, 6, 6, 48, 34, 955155, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
