# Generated by Django 5.0.1 on 2024-02-06 09:13

import uuid
from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    print("gen_uuid")
    MyModel = apps.get_model("core", "User")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
