# Generated by Django 5.0.1 on 2024-02-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_user_id_alter_user_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uuid',
            new_name='id',
        ),
    ]
