# Generated by Django 5.0.1 on 2024-02-09 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_post_postimage_bookmark_postlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='parent',
            new_name='reply_parent',
        ),
        migrations.AddField(
            model_name='post',
            name='respost_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='core.post'),
        ),
    ]
