# Generated by Django 5.0.1 on 2024-02-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_parent_post_reply_parent_post_respost_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='respost_parent',
            new_name='repost_parent',
        ),
    ]
