# Generated by Django 4.2.10 on 2024-02-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_bio_user_location_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='header_photo',
            field=models.ImageField(blank=True, null=True, upload_to='header_photos/'),
        ),
    ]
