# Generated by Django 4.2.10 on 2024-02-24 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_notification_alter_follow_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='notification_type_check',
        ),
        migrations.AddField(
            model_name='notification',
            name='repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repost_notification', to='core.post'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_notification', to='core.post'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'like'), ('reply', 'reply'), ('follow', 'follow'), ('repost', 'repost')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type', 'like'), ('like__isnull', False)), models.Q(('type', 'reply'), ('reply__isnull', False)), models.Q(('type', 'repost'), ('repost__isnull', False)), models.Q(('type', 'follow'), ('follow__isnull', False)), _connector='OR'), name='notification_type_check'),
        ),
    ]
