# Generated by Django 4.2.10 on 2024-03-12 03:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_visitrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(max_length=1000, unique=True)),
                ('posts', models.ManyToManyField(related_name='hashtags', to='core.post')),
            ],
        ),
    ]
