# Generated by Django 4.2.10 on 2024-03-12 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_post_content_hashtag'),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS pg_trgm;"),
    ]
