# Generated by Django 4.2.10 on 2024-03-12 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_enable_pg_trgm'),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS unaccent;"),
    ]
