# Generated by Django 4.2.10 on 2024-03-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_enable_unaccent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.TextField(max_length=1000),
        ),
    ]
