# Generated by Django 4.2.10 on 2024-03-23 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_hashtag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vistorId', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vistor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.visitor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
