# Generated by Django 4.2.10 on 2024-03-23 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_visitor_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='vistorId',
            new_name='visitorId',
        ),
    ]
