# Generated by Django 4.2.10 on 2024-03-23 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_vistorid_visitor_visitorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='vistor',
            new_name='visitor',
        ),
    ]
