# Generated by Django 4.2.10 on 2024-03-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_vistor_log_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='meta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
