# Generated by Django 4.2.10 on 2024-03-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_log_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
